sonar.projectKey=JLPTrial_database
sonar.projectName=JLPTrial Database
sonar.organization=jlptrial
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.sources=scripts,schemas

sonar.exclusions=**/__pycache__/**,**/outputs/**,**/.venv/**,**/venv/**
